"""initial migration

Revision ID: ae7d7f9cfdd9
Revises: 
Create Date: 2022-11-01 19:36:57.238871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7d7f9cfdd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ToDo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('module_code', sa.String(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ToDo_module_code'), 'ToDo', ['module_code'], unique=True)
    op.create_index(op.f('ix_ToDo_title'), 'ToDo', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ToDo_title'), table_name='ToDo')
    op.drop_index(op.f('ix_ToDo_module_code'), table_name='ToDo')
    op.drop_table('ToDo')
    # ### end Alembic commands ###
